<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="15416" started-at="2017-05-17T19:03:43Z" finished-at="2017-05-17T19:03:58Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="15416" started-at="2017-05-17T19:03:43Z" finished-at="2017-05-17T19:03:58Z">
      <class name="com.agm.Judi.tests.DemoTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.agm.Judi.tests.DemoTest@4dfa3a9d]" name="beforeMethod" is-config="true" duration-ms="657" started-at="2017-05-17T15:03:43Z" finished-at="2017-05-17T15:03:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="Test()[pri:0, instance:com.agm.Judi.tests.DemoTest@4dfa3a9d]" name="Test" duration-ms="12553" started-at="2017-05-17T15:03:44Z" finished-at="2017-05-17T15:03:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[true expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: true expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.agm.framework.FunctionLibraries.CommonFunctions.funLaunchURL(CommonFunctions.java:151)
	at com.agm.Judi.tests.DemoTest.Test(DemoTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.agm.Judi.tests.DemoTest@4dfa3a9d]" name="afterMethod" is-config="true" duration-ms="2182" started-at="2017-05-17T15:03:56Z" finished-at="2017-05-17T15:03:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.agm.Judi.tests.DemoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
